pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.architectury.dev/' }
    }
    // The Aprism packaging plugin is an included build so that example mods
    // can consume it via the plugins DSL without publishing.
    includeBuild 'aprism-packaging'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.architectury.dev/' }
    }
}

rootProject.name = 'Aprism'

include ':aprism-api'
include ':aprism-manifest'
include ':aprism-loader-core'
include ':aprism-conformance'
include ':examples:examplemod'
include ':examples:mixinproof'
