package com.aprism.loader.bedrock;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Maps Bedrock Edition version identifiers to the injection signature set
 * required to attach to that version's runtime.
 *
 * <p>Per FACT.md 9.8 the BE injection pipeline is <b>fail-closed</b>: if a BE
 * version has no entry in this database, injection MUST be refused rather
 * than attempted with unknown/guessed signatures. This protects against
 * attaching hooks at wrong offsets when Mojang changes the binary layout
 * between versions.
 *
 * <p>The database is deliberately a simple in-memory map for Alpha.1. Later
 * milestones will source it from the reverse-engineered signature database
 * generated by the BedrockAnalyzer header_generator pipeline (FACT.md 9.9).
 *
 * @author BlockConnect@StarsailsClover
 */
public final class BedrockVersionDatabase {

    /**
     * The signature set for one Bedrock version.
     *
     * @param beVersion      the Bedrock version identifier (e.g. {@code "26.2.0"})
     * @param signatureCount the number of known hook signatures for this version
     * @param supported      whether injection is supported for this version
     * @param notes          optional human-readable notes (may be empty)
     */
    public record VersionEntry(String beVersion, int signatureCount, boolean supported, String notes) {
        /**
         * @return true if this entry indicates injection is supported
         */
        public boolean isSupported() {
            return supported;
        }
    }

    private final Map<String, VersionEntry> entries = new HashMap<>();

    /**
     * Registers a version entry.
     *
     * @param entry the entry to register (keyed by {@link VersionEntry#beVersion()})
     */
    public void register(VersionEntry entry) {
        Objects.requireNonNull(entry, "entry must not be null");
        Objects.requireNonNull(entry.beVersion(), "beVersion must not be null");
        entries.put(normalize(entry.beVersion()), entry);
    }

    /**
     * Looks up the entry for a Bedrock version.
     *
     * <p>Fail-closed: if the version is unknown, returns {@code Optional.empty()}
     * and the caller MUST refuse injection.
     *
     * @param beVersion the Bedrock version identifier
     * @return the matching entry, or empty if unknown
     */
    public Optional<VersionEntry> lookup(String beVersion) {
        if (beVersion == null) {
            return Optional.empty();
        }
        return Optional.ofNullable(entries.get(normalize(beVersion)));
    }

    /**
     * Returns whether injection is supported for the given version.
     *
     * <p>Fail-closed: unknown versions and versions whose entry is marked
     * unsupported both return {@code false}.
     *
     * @param beVersion the Bedrock version identifier
     * @return true only if the version is known and supported
     */
    public boolean isSupported(String beVersion) {
        return lookup(beVersion).map(VersionEntry::isSupported).orElse(false);
    }

    /** @return the number of registered version entries */
    public int size() {
        return entries.size();
    }

    /**
     * Normalizes a version string for lookup. Strips a leading {@code v},
     * lowercases, and trims whitespace so that {@code "v26.2.0"},
     * {@code " 26.2.0 "}, and {@code "26.2.0"} all resolve to the same key.
     *
     * @param v the raw version string
     * @return the normalized key
     */
    private static String normalize(String v) {
        String s = v.trim().toLowerCase();
        if (s.startsWith("v")) {
            s = s.substring(1);
        }
        return s;
    }
}
